name: module_core
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  module_external_dependencies:
    path: '../module_external_dependencies'

  module_commons:
    path: '../module_commons'

  module_assets:
    path: '../module_assets'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  objectbox_generator: ^2.2.1

objectbox:
  output_dir: database

flutter:

  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.module_core
    iosBundleIdentifier: com.example.moduleCore
